// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owjvnehzgpemdjrktujp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93anZuZWh6Z3BlbWRqcmt0dWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTAxMDUsImV4cCI6MjA2NTY2NjEwNX0.pUQQ3gDyAl2NVx2z7Use4kin9lb027qSeGnXYD5R32M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);